[package]
name = "schan"
version = "0.1.0"
authors = ["mmarzullo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snow = { version = "0.6.2", features = ['ring'] }